workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.muzikology.live2share
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release 
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - muzikhubeka@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        # Uncomment when ready to publish to App Store
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $5VQCCAU76N
        issuer_id: $ee974663-a073-4df8-853a-cc95cecb4363
        submit_to_testflight: false
        # beta_groups:
        #   - App Beta Testers

  android-release:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - studentshare_keystore
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android release
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - muzikhubeka@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        # Uncomment when ready to publish to Google Play
        # credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
